name: GitHub Actions labwork
on:
  push:
    branches: [ "branch" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: cmake
      run: cmake -S . -B ./build/
    - name: make
      run: cd build && make
    - name: test
      run: ./build/
